update cennznet api and polkadot api version
cennznet/ui pull request #169
Opened 2022-02-15 04:13 UTC by KarishmaBothara

2022-02-27 22:49 UTC, ken-centrality requested changes
Looks good, there quite a few commented out code blocks, would be great if we can tidy them up before merge.

I noticed we've bumped up to use node `16`, then it's worth to update `.nvmrc` to `lts/gallium` to match with the requirement.

Also, does this resolve #170 and #172?

2022-02-27 22:49 UTC, ken-centrality commented on packages/app-accounts/src/Overview.tsx
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/app-accounts/src/Overview.tsx
>        </Button.Group>
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/app-explorer/src/BlockInfo/ByHash.tsx
> +
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/app-explorer/src/BlockInfo/ByHash.tsx
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/app-settings/src/General.tsx
>            <div className='ui--row'>
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/apps/webpack.config.js
> +      new webpack.optimize.SplitChunksPlugin(),
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/react-api/src/index.ts
>  };
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/react-api/src/ledger.ts
> +// }
Looks like the majority of `react-api/src/staking` files are commented out, worth to remove them to keep things tidy?

2022-02-27 22:49 UTC, ken-centrality commented on packages/react-components/src/Call.tsx
> +
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/react-components/src/Call.tsx
> +    // setExtracted({ hash, params, values });
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/app-address-book/src/Address.tsx
> +        {/*/>*/}
Remove the comment block if we don't need it anymore

2022-02-27 22:49 UTC, ken-centrality commented on packages/app-address-book/src/Address.tsx
>        </td>
Remove the comment block if we don't need it anymore

2022-03-01 00:43 UTC, KarishmaBothara commented
> Looks good, there quite a few commented out code blocks, would be great if we can tidy them up before merge.
> 
> I noticed we've bumped up to use node `16`, then it's worth to update `.nvmrc` to `lts/gallium` to match with the requirement.
> 
> Also, does this resolve #170 and #172?

thanks for looking thro' the PR.. I removed commented code blocks and updated .nvmrc
Yes, updated the code to resolve #170 and #172

2022-03-01 22:10 UTC, ken-centrality approved these changes

2022-03-01 22:10 UTC, ken-centrality commented
Looks good, but can you update .nvmrc to be `lts/gallium` instead of `16.0`, that will lock it to the LTS version of node 16, which is `16.13` atm

2022-03-02 05:07 UTC, KarishmaBothara commented
> lts/gallium

thanks.. done

2022-03-02 05:07 UTC, KarishmaBothara commented
> Looks good, but can you update .nvmrc to be `lts/gallium` instead of `16.0`, that will lock it to the LTS version of node 16, which is `16.13` atm

thanks done

2022-03-02 23:10 UTC, holygits commented
@KarishmaBothara shall we merge?

2022-03-02 23:10 UTC, holygits commented
need this so we can send txs to rata post update

2022-03-03 02:29 UTC, KarishmaBothara commented
> @KarishmaBothara shall we merge?

yes.. wll check the last four steps of the pipeline.. not sure why status is waiting for that

2022-03-03 04:03 UTC, closed without merging